<?php

namespace AppBundle\Repository;

/**
 * GoodPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodPublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
