<?php

namespace AppBundle\Repository;

/**
 * GoodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMonth($mediaplanId, $magazineId){
        $qb = $this->createQueryBuilder('m');
        $qb->select('m');
        $qb
            ->leftJoin('m.prices', 'price')
            ->leftJoin('price.goods', 'good')
            ->leftJoin('good.mediaplan', 'mediaplan')
            ->where('mediaplan.id = :mediaplanId')
            ->setParameter(':mediaplanId', $mediaplanId )
            ->groupBy('m.id')
            ->orderBy('m.title', 'ASC');
        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
