<?php

namespace AppBundle\Repository;

/**
 * GoodDesignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoodDesignRepository extends \Doctrine\ORM\EntityRepository
{
}
