<?php

namespace AppBundle\Repository;

/**
 * MagazineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $query
     * @return array
     * Поиск по
     *  названию журнала
     *  Названию издательства
     *  Нозологии
     *  Формату
     *  Распространению
     *  Импакт-фактор
     *  ФИО редактора
     */
    public function search($query, $activeNosology){
        $qb = $this->createQueryBuilder('s');
        $qb->select('s');
        $qb
           ->leftJoin('s.format', 'format')
           ->leftJoin('s.nosologies', 'nosologies')
           ->leftJoin('s.house', 'house')
           ->leftJoin('s.spread', 'spread')

            ->where("s.title LIKE '%$query%'")
            ->orWhere("s.impactFactor LIKE '%$query%'")
            ->orWhere("s.mainEditor LIKE '%$query%'")
            ->orWhere("format.title LIKE '%$query%'")
            ->orWhere("house.title LIKE '%$query%'")
            ->orWhere("spread.title LIKE '%$query%'")
            ->orWhere("nosologies.title LIKE '%$query%'");

        if ($activeNosology){
            $qb->andWhere('nosologies.id = :activeNosology')
                ->setParameter(':activeNosology', $activeNosology);
        }

        $qb->orderBy('s.id', 'ASC');

        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
