<?php

namespace AppBundle\Repository;

/**
 * MagazinePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagazinePublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
