<?php

namespace AppBundle\Repository;

/**
 * MediaplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaplanRepository extends \Doctrine\ORM\EntityRepository
{
}
