<?php

namespace AppBundle\Repository;

/**
 * NosologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NosologyRepository extends \Doctrine\ORM\EntityRepository
{
}
