<?php

namespace AppBundle\Repository;

/**
 * PublishingHouseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishingHouseRepository extends \Doctrine\ORM\EntityRepository
{
}
