<?php

namespace AppBundle\Repository;

/**
 * SpreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpreadRepository extends \Doctrine\ORM\EntityRepository
{
}
