<?php

namespace AppBundle\Repository;

/**
 * SpreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpreadRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForAutocomplete($title){
        $qb = $this->createQueryBuilder('b')
            ->select('b.title');
        if ($title){
            $qb->where("b.title LIKE '%$title%'");
        }

        return $qb->getQuery()->getResult();
    }
}
