<?php

namespace AppBundle\Repository;

/**
 * SpreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function filter($role, $text){
        if ($role == 'null') $role = null;
        if ($text == null) $text = '';

        $qb = $this->createQueryBuilder('u');
        $qb->select('u');
        $qb
            ->where("u.lastName LIKE '%".$text."%'")
            ->orWhere("u.firstName LIKE '%".$text."%'")
            ->orWhere("u.surName LIKE '%".$text."%'")
            ->orWhere("u.post LIKE '%".$text."%'")
            ->orWhere("u.username LIKE '%".$text."%'")
            ->orWhere("u.email LIKE '%".$text."%'");
            if ($role != null){
                $qb->andWhere("u.roles LIKE '%".$role."%'");
            }
            $qb->orderBy('u.lastName', 'ASC');
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}