# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    fos_user.doctrine_registry:
        alias: doctrine

    app.form.type.magazine:
        class: AppBundle\Form\MagazineType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.type.price:
        class: AppBundle\Form\PriceType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

